version:  '3.8'
services:
    mysql:
      image: mysql:8.0
      restart: on-failure
      ports:
        - '3306:3306'
      volumes:
        - /path/to/your/db:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: admin123
        MYSQL_DATABASE: car_race_docerize
        TZ: Europe/London

    nginx:
      image: nginx:alpine
      restart: on-failure
      volumes:
        - './public/:/usr/src/app'
        - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
      ports:
        - '8080:80'
      depends_on:
        - php

    php:
      build:
        context: .
        dockerfile: docker/php/Dockerfile
      volumes:
        - './:/usr/src/app'
      restart: on-failure
      env_file:
        - .env
      user: 1000:1000
