version:  '3.8'
services:
    database:
      container_name: database_mysql
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: admin123
        MYSQL_DATABASE: trainer_docker
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin123
      ports:
        - '4306:3306'
      volumes:
        - ./mysql:/var/lib/mysql

    nginx:
      container_name: nginx
      image: nginx:stable-alpine
      ports:
        - '8080:80'
      volumes:
        - ./app:/var/www/trainer
        - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
      depends_on:
        - php
        - database

    php:
      container_name: php
      build:
        context: .
        dockerfile: docker/php/Dockerfile
      volumes:
        - ./app:/var/www/trainer
      depends_on:
        - database
