parameters:
    photo_directory: '%kernel.project_dir%/public/uploads/photo'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $photoDirectory: '%photo_directory%'
            $shortPhotoDir: 'uploads/photo/'
            $localhostAddress: 'http://192.168.68.110:8080'
            $graphqlUserInfoAddress: '/graphql/user/info/query'

    # User
    App\User\Application\:
        resource: '../src/User/Application'

    App\User\Domain\:
        resource: '../src/User/Domain'

    App\User\Infrastructure\:
        resource: '../src/User/Infrastructure'

    App\User\UI\:
        resource: '../src/User/UI'

    App\User\UI\Controller\:
        resource: '../src/User/UI/Controller'
        tags: [ 'controller.service_arguments' ]

    App\User\UI\Controller\UserInfoController:
        parent: App\Shared\UI\Controller\AbstractQueryController
        public: false
        autowire: false
        autoconfigure: false
        tags: [ 'controller.service_arguments' ]

    App\User\Application\Handler\Command\:
        resource: '../src/User/Application/Handler/Command/'
        autoconfigure: false
        tags: [ { name: messenger.message_handler, bus: command.bus } ]

    App\User\Application\Handler\Query\:
        resource: '../src/User/Application/Handler/Query/'
        autoconfigure: false
        tags: [ { name: messenger.message_handler, bus: query.bus } ]

    App\User\Application\Resolver\UserInfoResolver:
        tags:
            - { name: overblog_graphql.resolver, alias: user_info_resolver }

    # Blog
    App\Blog\Application\:
        resource: '../src/Blog/Application'

    App\Blog\Domain\:
        resource: '../src/Blog/Domain'

    App\Blog\Infrastructure\:
        resource: '../src/Blog/Infrastructure'

    App\Blog\UI\:
        resource: '../src/Blog/UI'

    App\Blog\UI\Controller\:
        resource: '../src/Blog/UI/Controller'
        tags: [ 'controller.service_arguments' ]

    App\Blog\Application\Handler\Command\:
        resource: '../src/Blog/Application/Handler/Command/'
        autoconfigure: false
        tags: [ { name: messenger.message_handler, bus: command.bus } ]

    App\Blog\Application\Handler\Query\:
        resource: '../src/Blog/Application/Handler/Query/'
        autoconfigure: false
        tags: [ { name: messenger.message_handler, bus: query.bus } ]

    # Shared
    App\Shared\UI\Controller\:
        resource: '../src/Shared/UI/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\Shared\UI\Controller\AbstractQueryController:
        abstract: true
        arguments:
            - '@Overblog\GraphQLBundle\Request\BatchParser'
            - '@Overblog\GraphQLBundle\Request\Executor'
            - '@Overblog\GraphQLBundle\Request\Parser'
            - "%overblog_graphql.handle_cors%"
            - "%overblog_graphql.batching_method%"
