overblog_graphql:
    definitions:
        schema:
            user_info:
                query: UserInfo
        mappings:
            types:
                -
                    type: yaml
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: null
